COLORS = {
    "bg": "#F0F2F5",
    "surface": "#FFFFFF",
    "header_bg": "#1565C0",
    "header_text": "#FFFFFF",
    "primary": "#1976D2",
    "primary_hover": "#1565C0",
    "primary_light": "#E3F2FD",
    "azure": "#0078D4",
    "azure_hover": "#005A9E",
    "huawei": "#CF0A2C",
    "huawei_hover": "#A50824",
    "success": "#388E3C",
    "success_bg": "#E8F5E9",
    "error": "#D32F2F",
    "error_bg": "#FFEBEE",
    "warning": "#E65100",
    "warning_bg": "#FFF3E0",
    "text": "#212121",
    "text_secondary": "#616161",
    "border": "#CFD8DC",
    "section_border": "#BBDEFB",
    "row_alt": "#F8F9FA",
    "disabled": "#9E9E9E",
    "stop": "#C62828",
    "stop_hover": "#B71C1C",
}

FONTS = {
    "title": ("Segoe UI", 15, "bold"),
    "subtitle": ("Segoe UI", 9),
    "heading": ("Segoe UI", 11, "bold"),
    "label": ("Segoe UI", 10),
    "label_bold": ("Segoe UI", 10, "bold"),
    "input": ("Segoe UI", 10),
    "input_bold": ("Segoe UI", 10, "bold"),
    "button": ("Segoe UI", 10, "bold"),
    "button_lg": ("Segoe UI", 12, "bold"),
    "mono": ("Consolas", 9),
    "small": ("Segoe UI", 8),
    "tag": ("Segoe UI", 8, "bold"),
}
